acmeDirUrl: https://acme-staging-v02.api.letsencrypt.org/directory
acmeEmail: null
acmeTermsAccepted: false
kcertImage: nabsul/kcert:v1.2.0

env: {}

acmeKey:
  secretName: null
  keyName: key

acmeEabKey:
  secretName: kcert-prd-hmac-secret
  keyIdName: keyid
  hmacKeyName: hmac


showRenewButton: null

smtp:
  email: null
  host: null
  port: 25
  user: null
  secret:
    name: null
    key: password

names:
  serviceAccount: kcert
  clusterRole: kcert # Set to null to disable cluster-role resources (Useful when running in a namespace-constrained environment)
  clusterRoleBinding: kcert
  role: kcert
  roleBinding: kcert
  secret: kcert-smtp
  deployment: kcert
  service: kcert
  app: kcert

securityContext: []
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}

# Set this to false in order to generate a plain yaml template without the Helm custom labels
forHelm: true
